openapi: 3.0.3
info:
  title: BINNBOT API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /healthz:
    get:
      operationId: healthz
      responses:
        '200': { description: ok }
  /robots:
    get:
      operationId: listRobots
      responses:
        '200': { description: list }
    post:
      operationId: createRobot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RobotCreate'
      responses:
        '201': { description: created }
components:
  schemas:
    RobotCreate:
      type: object
      properties:
        name:
          type: string
          description: |
            Robot adı (opsiyonel). Boş bırakılırsa otomatik "Robot – {symbol} – {side}" olarak atanır.
        market:
          type: string
          enum: [spot, futures]
          default: spot
        symbol:
          type: string
        side:
          type: string
          enum: [buy, sell, long, short]
        schedule:
          $ref: '#/components/schemas/Schedule'
        params:
          type: object
