name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semver sürüm (örn: v1.0.0)"
        required: true
        default: "v1.0.0"
      notes:
        description: "Kısa açıklama (opsiyonel)"
        required: false
        default: ""

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate version
        run: |
          if [[ ! "${{ inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Bad version format: ${{ inputs.version }} (use vMAJOR.MINOR.PATCH)"
            exit 1
          fi
          echo "Version OK: ${{ inputs.version }}"

      - name: Create tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag -a "${{ inputs.version }}" -m "Release ${{ inputs.version }}"
          git push origin "${{ inputs.version }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ inputs.version }}
          body: ${{ inputs.notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
