name: Secrets Check

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    env:
      REQ_DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      REQ_DOCKERHUB_TOKEN:   ${{ secrets.DOCKERHUB_TOKEN }}
      REQ_STAGING_HOST:      ${{ secrets.STAGING_HOST }}
      REQ_STAGING_USER:      ${{ secrets.STAGING_USER }}
      REQ_STAGING_SSH_KEY:   ${{ secrets.STAGING_SSH_KEY }}
      REQ_STAGING_ENV_FILE:  ${{ secrets.STAGING_ENV_FILE }}
    steps:
      - name: Check required secrets
        run: |
          missing=()
          [[ -z "$REQ_DOCKERHUB_USERNAME" ]] && missing+=("DOCKERHUB_USERNAME")
          [[ -z "$REQ_DOCKERHUB_TOKEN"   ]] && missing+=("DOCKERHUB_TOKEN")
          [[ -z "$REQ_STAGING_HOST"      ]] && missing+=("STAGING_HOST")
          [[ -z "$REQ_STAGING_USER"      ]] && missing+=("STAGING_USER")
          [[ -z "$REQ_STAGING_SSH_KEY"   ]] && missing+=("STAGING_SSH_KEY")
          [[ -z "$REQ_STAGING_ENV_FILE"  ]] && missing+=("STAGING_ENV_FILE")

          if (( ${#missing[@]} > 0 )); then
            echo "❌ Missing secrets:"
            printf ' - %s\n' "${missing[@]}"
            exit 1
          else
            echo "✅ All required secrets are present."
          fi
